apiVersion: v1
kind: Namespace
metadata:
  name: bk


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kce-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bk 

  labels:
    app: kce
  name: kce
spec:
  selector:
    matchLabels:
      app: kce
  template:
    metadata:
      labels:
        app: kce
    spec:
      containers:
      - image: gcr.io/pgtm-jlong/kubernetes-client-example
        imagePullPolicy: Always
        name: kubernetes-client-example

