apiVersion: v1
kind: Namespace
metadata:
  name: bk

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kce-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bk
  labels:
    app: kubernetes-controller
  name: kubernetes-controller
spec:
  selector:
    matchLabels:
      app: kubernetes-controller
  template:
    metadata:
      labels:
        app: kubernetes-controller
    spec:
      containers:
        - image: gcr.io/pgtm-jlong/kubernetes-controller
          imagePullPolicy: Always
          name: kubernetes-controller

